"use strict";
// JS port of pmskit.specbuilder — propose min adequate schedule per size (B31.3)
// and assemble a class in the canonical schema. Uses window.PMSThickness + shared DB.
const SB_NPS=["1/2","3/4","1","1-1/4","1-1/2","2","2-1/2","3","4","5","6","8","10","12","14","16","18","20","24"];
const SB_PREF=["10","20","30","STD","40","60","XS","80","100","120","140","160","XXS"];
function sbMm(s){const m=/([0-9.]+)/.exec(s||'');return m?+m[1]:0;}
function sbSizes(f,t){const a=window.PMSCompare.nps(f);let b=window.PMSCompare.nps(t);if(a==null)return[];if(b==null)b=a;
  return SB_NPS.filter(x=>{const v=window.PMSCompare.nps(x);return v!=null&&v>=a-1e-9&&v<=b+1e-9;});}
function sbOrdered(pipe){const walls=pipe.wall||{};const byW={};
  for(const [lbl,w] of Object.entries(walls)){const cur=byW[w];
    if(cur==null||(SB_PREF.indexOf(lbl)>-1&&SB_PREF.indexOf(cur)>-1&&SB_PREF.indexOf(lbl)<SB_PREF.indexOf(cur)))byW[w]=lbl;}
  return Object.entries(byW).map(([w,lbl])=>[lbl,+w]).sort((a,b)=>a[1]-b[1]);}
// simplified: expose a build function taking already-resolved material entry
function sbBuild(opts){
  const {sch,mat,name,material_spec,grade,service,flange,ca_txt,temp,press,size_from,size_to,end,E,W,mt}=opts;
  const ca=sbMm(ca_txt);
  const pts=[];for(let i=0;i<Math.min(temp.length,press.length);i++){const t=+temp[i],pr=+press[i];if(!isNaN(t)&&!isNaN(pr))pts.push([t,pr]);}
  const nz=s=>(s||'').toUpperCase().replace(/[\s.]+/g,'');
  let material=null,best=null;
  for(const mm of (mat.materials||[])){if(nz(mm.spec)===nz(material_spec)){if(grade&&nz(mm.grade)===nz(grade)){material=mm;break;}best=best||mm;}}
  material=material||best;
  const detail=[];
  sbSizes(size_from,size_to).forEach(nps=>{
    const p=(sch.pipe||{})[nps]; if(!p)return;
    const D=p.od;
    if(!material){detail.push({nps,status:'no-stress-data',schedule:null,OD_mm:D});return;}
    const g=window.PMSThickness.governingCase(pts,D,T=>{ // interpolate S
        let s=material.s; if(!s)return null; s=s.map(a=>[+a[0],+a[1]]).sort((a,b)=>a[0]-b[0]);
        if(T<=s[0][0])return s[0][1]; if(T>=s[s.length-1][0])return s[s.length-1][1];
        for(let i=0;i<s.length-1;i++){const[t0,s0]=s[i],[t1,s1]=s[i+1];if(T>=t0&&T<=t1)return s0+(s1-s0)*(T-t0)/(t1-t0);}return null;
      },{E,W,family:material.family||'ferritic',c_mm:ca,mill_tol:mt});
    if(!g){detail.push({nps,status:'no-stress-data',schedule:null,OD_mm:D});return;}
    const req=g.tm; let chosen=null,wall=null;
    for(const [lbl,w] of sbOrdered(p)){if(w*(1-mt)>=req){chosen=lbl;wall=w;break;}}
    detail.push({nps,status:chosen?'OK':'no-adequate-schedule',schedule:chosen,wall_mm:wall,required_mm:req,OD_mm:D,governing:g});
  });
  // group consecutive same-schedule
  const comps=[];let run=[];const gtxt=grade?` GR.${grade}`:'';
  const flush=()=>{if(!run.length)return;const s=run[0].schedule;
    const stxt=['STD','XS','XXS'].includes(s)?s:(s?`SCH${s}`:null);
    comps.push({part:'PIPE',symbol:'(P)',size_from:run[0].nps,size_to:run[run.length-1].nps,
      size_raw:[run[0].nps,run[run.length-1].nps],
      description:s?`${material_spec}${gtxt}, SMLS, ${end}, ASME B36.10M [${stxt}]`:`${material_spec}${gtxt} — NO ADEQUATE SCHEDULE (review)`,
      notes:[],_sched:s,_req:run[0].required_mm});};
  detail.forEach(d=>{if(run.length&&d.schedule===run[run.length-1].schedule)run.push(d);else{flush();run=[d];}});flush();
  const cls={class:name,service,main_material:material_spec+gtxt,corrosion_allowance:ca_txt,
    flange_rating_face:flange,temp_C:temp.slice(),press_barg:press.slice(),
    particular_notes:'Auto-generated by Spec Builder (ASME B31.3).'+((mat.meta&&mat.meta.SYNTHETIC)?' SYNTHETIC stresses — replace with real datapack.':''),
    components:comps,component_count:comps.length};
  return {meta:{company:'SPEC-BUILDER',generator:'pms-toolkit spec-builder',code:'ASME B31.3',class_count:1,
    synthetic_stress:!!(mat.meta&&mat.meta.SYNTHETIC)},classes:[cls],sizing_detail:detail};
}
window.PMSSpec={build:sbBuild};
